name: Debug using tmate

on: [push]

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3

    - name: Setup tmate session
      #if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 15
