name: Debug via SSH

on: [push]

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        upterm-server: ssh://69.12.89.25:2222
